import type { ReadingText } from "./types";

export type ReadingLibraryTextKind = "dialog" | "text";

export type ReadingSample = {
  id: string;
  title: string;
  locale: "en" | "de";
  kind: ReadingLibraryTextKind;
  lines: string[];
};

const SAMPLE_READING_TEXTS: ReadingSample[] = [
  {
    id: "sample:reading:en:morning-plans",
    title: "Morning Plans",
    locale: "en",
    kind: "dialog",
    lines: [
      "Good morning! Did you sleep well?",
      "Pretty well, thanks. I woke up before my alarm for once.",
      "That sounds nice. Do you have a busy day ahead?",
      "A little. I have a meeting at ten and then I need to finish a report.",
      "Do you want to get coffee before you start?",
      "Yes, that would help. The kitchen is still quiet right now.",
      "Great. I can make tea too if you prefer.",
      "Coffee is perfect today. I need the extra energy.",
      "After work, are you doing anything fun?",
      "I might go for a walk if the weather stays clear.",
      "That sounds like a good plan. I may join you.",
      "Sure. Let's check in later this afternoon.",
    ],
  },
  {
    id: "sample:reading:en:at-the-library",
    title: "At the Library",
    locale: "en",
    kind: "dialog",
    lines: [
      "Excuse me, is this seat taken?",
      "No, go ahead. I'm only using the table for my notebook.",
      "Thank you. It's quieter here than downstairs.",
      "Yes, the reading room is usually calm in the afternoon.",
      "Are you studying for an exam?",
      "Not exactly. I'm preparing a presentation for Friday.",
      "What is it about?",
      "It's about city parks and how people use public spaces.",
      "That sounds interesting. I came here to read a novel.",
      "A novel sounds more relaxing than my presentation.",
      "Maybe, but I still have to return it tomorrow.",
      "Then I hope you have a peaceful hour.",
    ],
  },
  {
    id: "sample:reading:en:weekend-market",
    title: "Weekend Market",
    locale: "en",
    kind: "dialog",
    lines: [
      "Have you been to this market before?",
      "Yes, but only once. There are more stands today.",
      "The fruit looks fresh. I might buy some strawberries.",
      "Good idea. The bakery stand is also very popular.",
      "Do they sell bread or mostly cakes?",
      "Both. Their rye bread is excellent, and the lemon cake is dangerous.",
      "Dangerous sounds promising.",
      "It is. I bought a slice last week and immediately wanted another one.",
      "Let's look around first, then come back.",
      "Perfect. I also need tomatoes and maybe some flowers.",
      "Flowers would make the table look cheerful.",
      "Exactly. A small weekend luxury.",
    ],
  },
  {
    id: "sample:reading:en:travel-check-in",
    title: "Travel Check-In",
    locale: "en",
    kind: "dialog",
    lines: [
      "Hello, I have a reservation under Morgan.",
      "Welcome. Let me check that for you.",
      "Thank you. I booked a room for two nights.",
      "Yes, I see it here. Would you like a quiet room if one is available?",
      "That would be wonderful. I have an early meeting tomorrow.",
      "No problem. Your room is on the fourth floor, away from the elevator.",
      "Great. Is breakfast included?",
      "Yes, breakfast is served from seven to ten.",
      "And where can I find the conference rooms?",
      "Take the hallway to the left of reception. The signs will guide you.",
      "Perfect. Thank you for your help.",
      "You're very welcome. Enjoy your stay.",
    ],
  },
  {
    id: "sample:reading:en:doctor-appointment",
    title: "Doctor Appointment",
    locale: "en",
    kind: "dialog",
    lines: [
      "Hello, I have an appointment at three.",
      "Of course. Can I have your name, please?",
      "It's Taylor Reed.",
      "Thank you. Please take a seat for a moment.",
      "Do you know if the doctor is running late?",
      "Only about ten minutes. We will call you soon.",
      "That's fine. I brought a book with me.",
      "Perfect. Let us know if you need anything.",
    ],
  },
  {
    id: "sample:reading:en:neighbor-package",
    title: "Neighbor Package",
    locale: "en",
    kind: "dialog",
    lines: [
      "Hi, I think a package for me was delivered here.",
      "Yes, I have it by the door. The driver came this morning.",
      "Thank you for taking it in.",
      "No problem. It looked like rain, so I brought it inside.",
      "That was very kind of you.",
      "Happy to help. Is it something important?",
      "Just a lamp for my desk.",
      "Then I hope it makes your evening brighter.",
    ],
  },
  {
    id: "sample:reading:en:phone-repair",
    title: "Phone Repair",
    locale: "en",
    kind: "dialog",
    lines: [
      "My phone screen stopped responding this morning.",
      "Let me take a look. Did it fall or get wet?",
      "No, it was charging overnight.",
      "The battery looks fine, but the screen connector may be loose.",
      "Can you fix it today?",
      "I can try. It should take about two hours.",
      "Great. I need it for work tomorrow.",
      "We'll send you a message as soon as it is ready.",
    ],
  },
  {
    id: "sample:reading:en:cooking-dinner",
    title: "Cooking Dinner",
    locale: "en",
    kind: "dialog",
    lines: [
      "Do we have enough pasta for dinner?",
      "Yes, but we are almost out of sauce.",
      "I can make a quick tomato sauce.",
      "Good idea. Should I cut the onions?",
      "Please. And maybe wash the salad too.",
      "This is becoming a real team project.",
      "That means it will taste twice as good.",
      "Or at least we can blame each other if it doesn't.",
    ],
  },
  {
    id: "sample:reading:en:lost-umbrella",
    title: "Lost Umbrella",
    locale: "en",
    kind: "dialog",
    lines: [
      "Excuse me, did anyone turn in a blue umbrella?",
      "Let me check the lost and found box.",
      "I left it near the front row after the lecture.",
      "Is it dark blue with a wooden handle?",
      "Yes, that's the one.",
      "Then today is your lucky day.",
      "Wonderful. I was not ready to walk home in this rain.",
      "I completely understand. Here you go.",
    ],
  },
  {
    id: "sample:reading:en:planning-a-party",
    title: "Planning a Party",
    locale: "en",
    kind: "dialog",
    lines: [
      "How many people are coming on Saturday?",
      "About twelve, unless Max brings his cousins.",
      "Then we should buy extra snacks.",
      "Definitely. And more sparkling water.",
      "Do we need music?",
      "I made a playlist, but it may be too dramatic.",
      "Dramatic is fine after nine o'clock.",
      "Good. Then the party has a schedule now.",
    ],
  },
  {
    id: "sample:reading:en:job-interview",
    title: "Job Interview",
    locale: "en",
    kind: "dialog",
    lines: [
      "Thank you for coming in today.",
      "Thank you for inviting me. I'm glad to be here.",
      "Can you tell us about your last project?",
      "Sure. I helped organize a small team and improve our weekly process.",
      "What did you learn from that experience?",
      "I learned that clear communication saves a lot of time.",
      "That is very relevant for this role.",
      "I'm happy to hear that.",
    ],
  },
  {
    id: "sample:reading:en:bike-shop",
    title: "Bike Shop",
    locale: "en",
    kind: "dialog",
    lines: [
      "My bike makes a strange sound when I brake.",
      "Is it more of a squeak or a scrape?",
      "A squeak, especially going downhill.",
      "The brake pads may need cleaning or replacing.",
      "Can you check it before the weekend?",
      "Yes, bring it in tomorrow morning.",
      "Great. I planned a ride on Sunday.",
      "Then we'll make sure it is ready.",
    ],
  },
  {
    id: "sample:reading:en:movie-night",
    title: "Movie Night",
    locale: "en",
    kind: "dialog",
    lines: [
      "Do you want to watch a comedy or a mystery?",
      "A mystery, but not one that is too stressful.",
      "So a gentle mystery?",
      "Exactly. Something with tea, rain, and one missing necklace.",
      "That is very specific.",
      "I know what I like.",
      "I'll find three options.",
      "Perfect. I'll make popcorn.",
    ],
  },
  {
    id: "sample:reading:en:community-garden",
    title: "Community Garden",
    locale: "en",
    kind: "dialog",
    lines: [
      "Are these tomatoes yours?",
      "Yes, but please take a few if you want.",
      "Really? They look beautiful.",
      "There are more than I can eat this week.",
      "I can trade you some basil.",
      "That sounds perfect for dinner.",
      "This garden is becoming a tiny market.",
      "A friendly one, at least.",
    ],
  },
  {
    id: "sample:reading:en:museum-tickets",
    title: "Museum Tickets",
    locale: "en",
    kind: "dialog",
    lines: [
      "Good afternoon. Are there still tickets for the photography exhibit?",
      "Yes, there are. Would you like tickets for today?",
      "Please. Two adults, if possible.",
      "Of course. The exhibit is on the second floor and closes at six.",
      "Is there a guided tour this afternoon?",
      "There is one at four, but it is almost full.",
      "Can we join if we arrive a few minutes early?",
      "Yes, I recommend being there ten minutes before it starts.",
      "Great. Is photography allowed inside the exhibit?",
      "Only without flash, and not in the final room.",
      "Good to know. Thank you for explaining everything.",
      "You're welcome. I hope you enjoy the visit.",
    ],
  },
  {
    id: "sample:reading:en:quiet-morning",
    title: "A Quiet Morning",
    locale: "en",
    kind: "text",
    lines: [
      "The street was still quiet when the first bakery opened its door. A soft smell of bread moved through the cool air, and the windows slowly caught the morning light.",
      "For a few minutes, the city felt gentle and unhurried. Someone swept the sidewalk, a cyclist passed without speaking, and the day began without any need to announce itself.",
      "At the corner, a delivery truck stopped with a soft hiss of brakes. The driver stacked crates beside a cafe door and nodded to a woman walking a small dog in a red coat.",
      "By the time the first bus arrived, the spell was already changing. More footsteps joined the pavement, more voices crossed the street, and the quiet morning became an ordinary one.",
      "Still, the memory of those first minutes stayed behind like warmth in a cup. It made the rest of the day feel a little less sharp.",
    ],
  },
  {
    id: "sample:reading:en:small-habits",
    title: "Small Habits",
    locale: "en",
    kind: "text",
    lines: [
      "Small habits rarely feel important while they are happening. A glass of water, a short walk, a note written before bed: each one seems almost too simple to count.",
      "But simple actions become a kind of quiet architecture. Over time, they shape the room we live in, even when no one else can see the work.",
      "A person who stretches for five minutes every morning may not notice much after one week. After a month, though, the body begins to expect that kindness and asks for it when it is missing.",
      "The same is true for attention. When we regularly pause before answering, tidy one small surface, or write down one honest sentence, we teach ourselves what kind of life we are building.",
      "Progress does not always arrive with a dramatic sound. Sometimes it sounds like a kettle, a closing notebook, or shoes by the door.",
    ],
  },
  {
    id: "sample:reading:en:rain-at-the-window",
    title: "Rain at the Window",
    locale: "en",
    kind: "text",
    lines: [
      "Rain changes the sound of a room. It softens the edges of traffic and gives every pause a little rhythm. Even ordinary objects seem more patient in rainy weather.",
      "A cup waits on the table, a book lies open, and the window keeps the whole afternoon at a comfortable distance.",
      "Outside, people walk faster, shoulders raised, umbrellas leaning into the wind. Inside, time feels slower, as if the room has decided to breathe more deeply.",
      "There is comfort in hearing the weather without needing to enter it. The rain speaks in taps and streams, and each sound makes the silence around it easier to notice.",
      "When the clouds finally lift, the street shines with reflected light. The room returns to itself, but a little of the rainy calm remains.",
    ],
  },
  {
    id: "sample:reading:en:learning-a-route",
    title: "Learning a Route",
    locale: "en",
    kind: "text",
    lines: [
      "The first time you walk a new route, every corner asks for attention. You remember the yellow door, the loud crossing, and the tree with roots pushing up the pavement.",
      "After a while, the route becomes part of you. Your feet know when to turn, and your thoughts are free to travel somewhere else.",
      "You begin to notice smaller things: which garden smells of mint, which window always has music behind it, and where the pavement stays wet after rain.",
      "A familiar route is not boring. It is a shelf where memory places tiny objects, one after another, until the walk becomes a map of ordinary days.",
      "Then, when you take the route after a long absence, it greets you strangely. Some details have changed, but your body still remembers the shape of the way.",
    ],
  },
  {
    id: "sample:reading:en:evening-light",
    title: "Evening Light",
    locale: "en",
    kind: "text",
    lines: [
      "Evening light makes familiar rooms look newly arranged. It rests on shelves, slides across the floor, and turns dust in the air into something almost golden.",
      "Nothing has changed, but everything feels briefly worth noticing. That may be one of the small gifts of the end of the day.",
      "The chair by the window becomes less like furniture and more like an invitation. The books on the table seem quieter, as if they are waiting for tomorrow.",
      "Outside, the sounds of traffic grow softer and more spread out. A neighbor closes a balcony door, someone laughs in the courtyard, and the sky slowly loses its blue.",
      "Evening does not solve anything, but it lowers its voice. Sometimes that is enough to make a person feel ready to begin again in the morning.",
    ],
  },
  {
    id: "sample:reading:de:im-cafe",
    title: "Im Cafe",
    locale: "de",
    kind: "dialog",
    lines: [
      "Guten Morgen! Ist hier noch frei?",
      "Ja, natürlich. Setzen Sie sich gerne.",
      "Danke. Kommen Sie oft in dieses Café?",
      "Ja, eigentlich fast jede Woche. Der Kaffee hier ist sehr gut.",
      "Das habe ich auch gehört. Ich bin heute zum ersten Mal hier.",
      "Dann müssen Sie unbedingt den Cappuccino probieren.",
      "Gute Idee. Haben Sie heute noch viel vor?",
      "Nicht besonders. Ich muss später noch einkaufen und ein paar E-Mails beantworten.",
      "Das klingt entspannt. Ich treffe mich nachher mit einem Freund in der Stadt.",
      "Schön. Wie lange kennen Sie Ihren Freund schon?",
      "Seit der Schulzeit. Wir sehen uns nicht so oft, deshalb freue ich mich auf das Treffen.",
      "Das kann ich verstehen. Alte Freundschaften sind etwas Besonderes.",
      "Da haben Sie recht. Was machen Sie beruflich?",
      "Ich arbeite in einem Büro als Projektmanager. Und Sie?",
      "Ich bin Lehrer und unterrichte Deutsch und Geschichte.",
      "Interessant. Macht Ihnen die Arbeit Spaß?",
      "Ja, sehr. Die Arbeit mit den Schülern ist abwechslungsreich.",
      "Das glaube ich. Oh, unser Kaffee kommt gerade.",
      "Perfekt. Dann wünsche ich Ihnen einen schönen Tag.",
      "Danke, Ihnen auch. Vielleicht sieht man sich ja wieder hier.",
      "Ja, vielleicht. Auf Wiedersehen!",
      "Auf Wiedersehen!",
    ],
  },
  {
    id: "sample:reading:de:am-bahnhof",
    title: "Am Bahnhof",
    locale: "de",
    kind: "dialog",
    lines: [
      "Entschuldigung, fährt dieser Zug nach Salzburg?",
      "Ja, aber nur bis Linz direkt. Danach müssen Sie umsteigen.",
      "Danke. Wissen Sie, auf welchem Gleis der Anschluss fährt?",
      "Ich glaube auf Gleis fünf, aber schauen Sie lieber auf die Anzeige.",
      "Gute Idee. Reisen Sie auch nach Salzburg?",
      "Nein, ich fahre nur bis Wels. Ich besuche dort meine Schwester.",
      "Das klingt schön. Ich fahre zu einer Konferenz.",
      "Dann hoffe ich, dass alles pünktlich ist.",
      "Ich auch. Der Fahrplan sieht heute eigentlich gut aus.",
      "Dann haben wir Glück. Der Zug kommt gerade.",
      "Perfekt. Vielen Dank für Ihre Hilfe.",
      "Gern geschehen. Gute Reise!",
    ],
  },
  {
    id: "sample:reading:de:beim-einkaufen",
    title: "Beim Einkaufen",
    locale: "de",
    kind: "dialog",
    lines: [
      "Hallo, wissen Sie, wo ich Reis finde?",
      "Ja, der Reis steht im zweiten Gang, gleich neben den Nudeln.",
      "Super, danke. Ich koche heute Abend für Freunde.",
      "Was gibt es denn?",
      "Ein Curry mit Gemüse und Kokosmilch.",
      "Das klingt lecker. Brauchen Sie auch frischen Koriander?",
      "Ja, stimmt. Den hätte ich fast vergessen.",
      "Der ist vorne beim Gemüse, neben der Petersilie.",
      "Danke für den Tipp. Kochen Sie auch gern?",
      "Sehr gern, aber meistens eher einfache Gerichte.",
      "Einfach ist oft am besten.",
      "Genau. Dann viel Erfolg beim Abendessen!",
    ],
  },
  {
    id: "sample:reading:de:nach-der-arbeit",
    title: "Nach der Arbeit",
    locale: "de",
    kind: "dialog",
    lines: [
      "Bist du schon fertig für heute?",
      "Fast. Ich muss nur noch eine Nachricht beantworten.",
      "Ich warte gern. Wollen wir danach noch spazieren gehen?",
      "Ja, das wäre schön. Ich war den ganzen Tag drinnen.",
      "Der Park ist um diese Zeit sehr angenehm.",
      "Stimmt. Und vielleicht holen wir uns unterwegs ein Eis.",
      "Das klingt nach einem guten Plan.",
      "Hattest du einen stressigen Tag?",
      "Ein bisschen, aber jetzt ist das Wichtigste erledigt.",
      "Dann hast du dir eine Pause verdient.",
      "Danke. Gib mir noch fünf Minuten, dann können wir los.",
      "Alles klar. Ich hole schon mal meine Jacke.",
    ],
  },
  {
    id: "sample:reading:de:arzttermin",
    title: "Arzttermin",
    locale: "de",
    kind: "dialog",
    lines: [
      "Guten Tag, ich habe um drei Uhr einen Termin.",
      "Natürlich. Wie ist Ihr Name?",
      "Taylor Reed.",
      "Danke. Nehmen Sie bitte noch kurz Platz.",
      "Wissen Sie, ob die Ärztin Verspätung hat?",
      "Nur ungefähr zehn Minuten. Wir rufen Sie gleich auf.",
      "Das ist in Ordnung. Ich habe ein Buch dabei.",
      "Sehr gut. Melden Sie sich, wenn Sie etwas brauchen.",
    ],
  },
  {
    id: "sample:reading:de:paket-beim-nachbarn",
    title: "Paket beim Nachbarn",
    locale: "de",
    kind: "dialog",
    lines: [
      "Hallo, ich glaube, ein Paket für mich wurde hier abgegeben.",
      "Ja, es steht neben der Tür. Der Fahrer war heute Vormittag da.",
      "Danke, dass Sie es angenommen haben.",
      "Gern. Es sah nach Regen aus, also habe ich es reingeholt.",
      "Das war wirklich nett.",
      "Kein Problem. Ist es etwas Wichtiges?",
      "Nur eine Lampe für meinen Schreibtisch.",
      "Dann hoffe ich, dass sie Ihren Abend heller macht.",
    ],
  },
  {
    id: "sample:reading:de:handy-reparatur",
    title: "Handy-Reparatur",
    locale: "de",
    kind: "dialog",
    lines: [
      "Mein Handybildschirm reagiert seit heute Morgen nicht mehr.",
      "Ich schaue es mir an. Ist es heruntergefallen oder nass geworden?",
      "Nein, es lag die ganze Nacht am Ladegerät.",
      "Der Akku sieht gut aus, aber vielleicht ist ein Stecker locker.",
      "Können Sie es heute reparieren?",
      "Ich kann es versuchen. Es dauert ungefähr zwei Stunden.",
      "Super. Ich brauche es morgen für die Arbeit.",
      "Wir melden uns, sobald es fertig ist.",
    ],
  },
  {
    id: "sample:reading:de:abendessen-kochen",
    title: "Abendessen kochen",
    locale: "de",
    kind: "dialog",
    lines: [
      "Haben wir genug Nudeln für heute Abend?",
      "Ja, aber die Soße ist fast leer.",
      "Ich kann schnell eine Tomatensoße machen.",
      "Gute Idee. Soll ich die Zwiebeln schneiden?",
      "Bitte. Und vielleicht auch den Salat waschen.",
      "Das wird ja ein echtes Teamprojekt.",
      "Dann schmeckt es doppelt so gut.",
      "Oder wir können uns gegenseitig die Schuld geben.",
    ],
  },
  {
    id: "sample:reading:de:verlorener-regenschirm",
    title: "Verlorener Regenschirm",
    locale: "de",
    kind: "dialog",
    lines: [
      "Entschuldigung, wurde ein blauer Regenschirm abgegeben?",
      "Ich schaue kurz in der Fundkiste nach.",
      "Ich habe ihn nach der Vorlesung in der ersten Reihe vergessen.",
      "Ist er dunkelblau mit einem Holzgriff?",
      "Ja, genau der.",
      "Dann haben Sie heute Glück.",
      "Wunderbar. Ich wollte nicht im Regen nach Hause laufen.",
      "Das kann ich gut verstehen. Hier ist er.",
    ],
  },
  {
    id: "sample:reading:de:party-planen",
    title: "Party planen",
    locale: "de",
    kind: "dialog",
    lines: [
      "Wie viele Leute kommen am Samstag?",
      "Ungefähr zwölf, außer Max bringt seine Cousins mit.",
      "Dann sollten wir mehr Snacks kaufen.",
      "Auf jeden Fall. Und mehr Sprudelwasser.",
      "Brauchen wir Musik?",
      "Ich habe eine Playlist gemacht, aber sie ist vielleicht zu dramatisch.",
      "Dramatisch ist nach neun Uhr völlig okay.",
      "Gut. Dann hat die Party jetzt einen Zeitplan.",
    ],
  },
  {
    id: "sample:reading:de:bewerbungsgespraech",
    title: "Bewerbungsgespräch",
    locale: "de",
    kind: "dialog",
    lines: [
      "Vielen Dank, dass Sie heute gekommen sind.",
      "Danke für die Einladung. Ich freue mich, hier zu sein.",
      "Können Sie uns von Ihrem letzten Projekt erzählen?",
      "Gerne. Ich habe ein kleines Team organisiert und unseren Wochenablauf verbessert.",
      "Was haben Sie daraus gelernt?",
      "Ich habe gelernt, dass klare Kommunikation viel Zeit spart.",
      "Das ist für diese Stelle sehr wichtig.",
      "Das freut mich zu hören.",
    ],
  },
  {
    id: "sample:reading:de:fahrradladen",
    title: "Fahrradladen",
    locale: "de",
    kind: "dialog",
    lines: [
      "Mein Fahrrad macht beim Bremsen ein komisches Geräusch.",
      "Ist es eher ein Quietschen oder ein Kratzen?",
      "Ein Quietschen, besonders bergab.",
      "Vielleicht müssen die Bremsbeläge gereinigt oder ersetzt werden.",
      "Können Sie es vor dem Wochenende anschauen?",
      "Ja, bringen Sie es morgen früh vorbei.",
      "Super. Ich habe am Sonntag eine Tour geplant.",
      "Dann sorgen wir dafür, dass es bereit ist.",
    ],
  },
  {
    id: "sample:reading:de:filmabend",
    title: "Filmabend",
    locale: "de",
    kind: "dialog",
    lines: [
      "Willst du eine Komödie oder einen Krimi sehen?",
      "Einen Krimi, aber nicht zu spannend.",
      "Also einen gemütlichen Krimi?",
      "Genau. Mit Tee, Regen und einer verschwundenen Halskette.",
      "Das ist sehr genau.",
      "Ich weiß eben, was ich mag.",
      "Ich suche drei Möglichkeiten raus.",
      "Perfekt. Ich mache Popcorn.",
    ],
  },
  {
    id: "sample:reading:de:gemeinschaftsgarten",
    title: "Gemeinschaftsgarten",
    locale: "de",
    kind: "dialog",
    lines: [
      "Sind das Ihre Tomaten?",
      "Ja, aber nehmen Sie gern ein paar.",
      "Wirklich? Sie sehen wunderschön aus.",
      "Es sind mehr, als ich diese Woche essen kann.",
      "Ich kann Ihnen dafür Basilikum geben.",
      "Das passt perfekt zum Abendessen.",
      "Dieser Garten wird langsam ein kleiner Markt.",
      "Aber wenigstens ein freundlicher.",
    ],
  },
  {
    id: "sample:reading:de:museumskarten",
    title: "Museumskarten",
    locale: "de",
    kind: "dialog",
    lines: [
      "Guten Tag. Gibt es noch Karten für die Fotoausstellung?",
      "Ja, die gibt es. Möchten Sie Karten für heute?",
      "Bitte. Zwei Erwachsene, wenn möglich.",
      "Natürlich. Die Ausstellung ist im zweiten Stock und schließt um sechs.",
      "Gibt es heute Nachmittag eine Führung?",
      "Ja, um vier Uhr, aber sie ist fast voll.",
      "Können wir teilnehmen, wenn wir ein paar Minuten früher da sind?",
      "Ja, ich empfehle, zehn Minuten vorher dort zu sein.",
      "Super. Darf man in der Ausstellung fotografieren?",
      "Nur ohne Blitz und nicht im letzten Raum.",
      "Gut zu wissen. Danke für die Erklärung.",
      "Sehr gern. Ich wünsche Ihnen einen schönen Besuch.",
    ],
  },
  {
    id: "sample:reading:de:ruhiger-morgen",
    title: "Ein ruhiger Morgen",
    locale: "de",
    kind: "text",
    lines: [
      "Die Straße war noch still, als die erste Bäckerei ihre Tür öffnete. Ein weicher Duft von Brot zog durch die kühle Luft, und die Fenster fingen langsam das Morgenlicht ein.",
      "Für ein paar Minuten wirkte die Stadt freundlich und ohne Eile. Jemand fegte den Gehweg, ein Radfahrer fuhr schweigend vorbei, und der Tag begann ganz leise.",
      "An der Ecke hielt ein Lieferwagen mit einem leisen Zischen der Bremsen. Der Fahrer stellte Kisten neben eine Cafétür und nickte einer Frau zu, die mit einem kleinen Hund im roten Mantel vorbeiging.",
      "Als der erste Bus kam, veränderte sich der Zauber schon. Mehr Schritte füllten den Gehweg, mehr Stimmen kreuzten die Straße, und der stille Morgen wurde ein gewöhnlicher.",
      "Trotzdem blieb die Erinnerung an diese ersten Minuten zurück wie Wärme in einer Tasse. Sie machte den Rest des Tages ein wenig weniger scharf.",
    ],
  },
  {
    id: "sample:reading:de:kleine-gewohnheiten",
    title: "Kleine Gewohnheiten",
    locale: "de",
    kind: "text",
    lines: [
      "Kleine Gewohnheiten fühlen sich selten wichtig an, während sie passieren. Ein Glas Wasser, ein kurzer Spaziergang, eine Notiz vor dem Schlafen: Jede Handlung wirkt fast zu einfach, um zu zählen.",
      "Aber einfache Dinge werden mit der Zeit zu einer stillen Architektur. Sie formen den Raum, in dem wir leben, auch wenn niemand die Arbeit sieht.",
      "Wer sich jeden Morgen fünf Minuten dehnt, merkt nach einer Woche vielleicht kaum etwas. Nach einem Monat beginnt der Körper aber, diese Freundlichkeit zu erwarten und sie zu vermissen.",
      "So ist es auch mit Aufmerksamkeit. Wenn wir regelmäßig kurz innehalten, eine kleine Fläche aufräumen oder einen ehrlichen Satz aufschreiben, zeigen wir uns selbst, welches Leben wir bauen.",
      "Fortschritt kommt nicht immer mit einem großen Geräusch. Manchmal klingt er wie ein Wasserkessel, ein geschlossenes Notizbuch oder Schuhe neben der Tür.",
    ],
  },
  {
    id: "sample:reading:de:regen-am-fenster",
    title: "Regen am Fenster",
    locale: "de",
    kind: "text",
    lines: [
      "Regen verändert den Klang eines Zimmers. Er macht den Verkehr weicher und gibt jeder Pause einen kleinen Rhythmus. Sogar gewöhnliche Gegenstände wirken bei Regen geduldiger.",
      "Eine Tasse wartet auf dem Tisch, ein Buch liegt offen da, und das Fenster hält den ganzen Nachmittag in angenehmer Entfernung.",
      "Draußen gehen die Menschen schneller, mit hochgezogenen Schultern und Schirmen gegen den Wind. Drinnen fühlt sich die Zeit langsamer an, als hätte das Zimmer beschlossen, tiefer zu atmen.",
      "Es ist tröstlich, das Wetter zu hören, ohne hinausgehen zu müssen. Der Regen spricht in Tropfen und kleinen Strömen, und jedes Geräusch macht die Stille darum herum deutlicher.",
      "Wenn die Wolken sich endlich heben, glänzt die Straße im Licht. Das Zimmer wird wieder zu sich selbst, aber ein wenig von der Ruhe des Regens bleibt.",
    ],
  },
  {
    id: "sample:reading:de:einen-weg-lernen",
    title: "Einen Weg lernen",
    locale: "de",
    kind: "text",
    lines: [
      "Wenn man einen neuen Weg zum ersten Mal geht, verlangt jede Ecke Aufmerksamkeit. Man merkt sich die gelbe Tür, die laute Kreuzung und den Baum, dessen Wurzeln den Gehweg anheben.",
      "Nach einer Weile wird der Weg ein Teil von einem. Die Füße wissen, wann sie abbiegen müssen, und die Gedanken dürfen woandershin gehen.",
      "Dann bemerkt man kleinere Dinge: welcher Garten nach Minze riecht, hinter welchem Fenster immer Musik läuft und wo der Gehweg nach Regen lange nass bleibt.",
      "Ein vertrauter Weg ist nicht langweilig. Er ist ein Regal, in das die Erinnerung kleine Gegenstände stellt, bis der Spaziergang zu einer Karte gewöhnlicher Tage wird.",
      "Wenn man den Weg nach langer Zeit wieder geht, begrüßt er einen seltsam vertraut. Manche Details haben sich verändert, aber der Körper kennt die Form des Weges noch.",
    ],
  },
  {
    id: "sample:reading:de:abendlicht",
    title: "Abendlicht",
    locale: "de",
    kind: "text",
    lines: [
      "Abendlicht lässt vertraute Zimmer neu aussehen. Es liegt auf den Regalen, gleitet über den Boden und verwandelt Staub in der Luft in etwas beinahe Goldenes.",
      "Nichts hat sich verändert, aber für einen Moment wirkt alles sehenswert. Vielleicht ist das eines der kleinen Geschenke am Ende des Tages.",
      "Der Stuhl am Fenster ist plötzlich weniger ein Möbelstück als eine Einladung. Die Bücher auf dem Tisch wirken stiller, als warteten sie schon auf morgen.",
      "Draußen werden die Geräusche des Verkehrs weicher und weiter auseinandergezogen. Ein Nachbar schließt eine Balkontür, jemand lacht im Hof, und der Himmel verliert langsam sein Blau.",
      "Der Abend löst nicht alles, aber er senkt die Stimme. Manchmal reicht das, damit ein Mensch am nächsten Morgen wieder anfangen kann.",
    ],
  },
];

export type ReadingLibraryText = ReadingText & {
  locale: ReadingSample["locale"];
  kind: ReadingLibraryTextKind;
};

export function createSampleReadingTexts(): ReadingLibraryText[] {
  return SAMPLE_READING_TEXTS.map((sample, index) => ({
    id: sample.id,
    title: sample.title,
    body: sample.lines.join("\n\n"),
    source: "module",
    locale: sample.locale,
    kind: sample.kind,
    createdAt: index,
    updatedAt: index,
  }));
}

export const READING_LIBRARY_TEXTS = createSampleReadingTexts();
